import './globals.css'
import Footer from './components/Footer'
import styles from './page.module.css'

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="container">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}